name: Setup pnpm
description: Install pnpm package manager
branding:
  icon: package
  color: orange
inputs:
  version:
    description: Version of pnpm to install
    required: false
  dest:
    description: Where to store pnpm files
    required: false
    default: ~/setup-pnpm
  run_install:
    description: If specified, run `pnpm install`
    required: false
    default: 'null'
  package_json_file:
    description: File path to the package.json to read "packageManager" configuration
    required: false
    default: 'package.json'
  nodejs_bundled:
    description: When set to true, @pnpm/exe, which is a Node.js bundled package, will be installed.
    required: false
    default: 'false'
runs:
  using: node16
  main: dist/index.js
  post: dist/index.js
