name: Setup PNPM
description: Install PNPM package manager
branding:
  icon: package
  color: orange
inputs:
  version:
    description: Version of PNPM to install
    required: true
  dest:
    description: Where to store PNPM files
    required: false
    default: ~/setup-pnpm
  run_install:
    description: If specified, run `pnpm install`
    required: false
    default: 'null'
runs:
  using: node12
  main: dist/index.js
  post: dist/index.js
