name: Setup pnpm
description: Install pnpm package manager
branding:
  icon: package
  color: orange
inputs:
  version:
    description: Version of pnpm to install
    required: false
  dest:
    description: Where to store pnpm files
    required: false
    default: ~/setup-pnpm
  run_install:
    description: If specified, run `pnpm install`
    required: false
    default: 'null'
runs:
  using: node16
  main: dist/index.js
  post: dist/index.js
