name: Setup pnpm
description: Install pnpm package manager
branding:
  icon: package
  color: orange
inputs:
  version:
    description: Version of pnpm to install
    required: false
  dest:
    description: Where to store pnpm files
    required: false
    default: ~/setup-pnpm
  run_install:
    description: If specified, run `pnpm install`
    required: false
    default: 'null'
  package_json_file:
    description: File path to the package.json to read "packageManager" configuration
    required: false
    default: 'package.json'
  standalone:
    description: When set to true, @pnpm/exe, which is a Node.js bundled package, will be installed, enabling using pnpm without Node.js.
    required: false
    default: 'false'
outputs:
  dest:
    description: Expanded path of inputs#dest
  bin_dest:
    description: Location of `pnpm` and `pnpx` command
runs:
  using: node20
  main: dist/index.js
  post: dist/index.js
